import { color, radius, space } from "./tokens";

/** violetInk -> violet-ink, ink2 -> ink-2 */
function kebab(name: string): string {
  return name.replace(/([a-z])([A-Z0-9])/g, "$1-$2").toLowerCase();
}

export function cssVariables(): string {
  const lines = [
    ...Object.entries(color).map(([key, value]) => `  --hr-${kebab(key)}: ${value};`),
    ...Object.entries(radius).map(([key, value]) => `  --hr-radius-${key}: ${value}px;`),
    ...Object.entries(space).map(([key, value]) => `  --hr-space-${key}: ${value}px;`),
  ];
  return `:root {\n${lines.join("\n")}\n}\n`;
}

export function tokensCss(): string {
  return [
    "/* Generated by `npm run tokens:css` from packages/tokens/src/index.ts.",
    "   Do not edit by hand — edit the tokens and re-run. */",
    "",
    cssVariables(),
  ].join("\n");
}
